name: Docker Compose CI
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose up -d

    - name: Test apache
      run: |
        cd test
        curl localhost:80

    - name: Test phpmyadmin
      run: |
        cd test
        curl localhost:8080

    - name: Stop containers
      run: docker compose down
